name: Deploy and Start

on:
  workflow_run:
    workflows: ["Stop and Clean"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-and-start:
    name: Deploy New JAR and Start Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  

    - name: Download latest JAR file from GitHub release
      id: download-jar
      run: |
        latest_release=$(curl -s https://api.github.com/repos/manuo9/2024/releases/latest | jq -r '.assets[] | select(.name | endswith(".jar")) | .browser_download_url')
        wget "$latest_release" -O latest.jar

    - name: Copy JAR file to EC2
      run: scp -i ${{ secrets.EC2_SSH_KEY }} latest.jar ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/home/${{ secrets.USERNAME }}/app

    - name: Run JAR file on EC2
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "cd /home/${{ secrets.USERNAME }}/app && sudo nohup java -jar latest.jar > /dev/null 2>&1 &"
